### ISSUE TITLE
Size of repo

### ISSUE THREAD

**Issue by CarloMara** [NSkelsey/monopticon#2]
Hi Nick,

The repo is super big. This impacts clone times and builder times. Running `du` on the report suggests that the files located in `contrib/screens` are the biggest offenders. 

Maybe we should consider converting the gifs to webm, this should reduce filesize while increasing quality.

Carlo

**Comment by NSkelsey** [comment]
Okay,

I agree with this point. Lets:

- [x] remove the gifs (and remove all of the history of the gifs in the tree...)
- [x] cleanup the commit history - wireshark - (this will require a hard reset of forks)

As of now the total download size is 94.83 MiB and the object count is 7954.

- [x] specify cleanly the files to be included in source tarballs.
     - move `src/expirements` into `contrib`
     - specify something like a `.gitignore` but for file archives which have been made via:
```
>  git archive --format=tar.gz --prefix=monopticon-0.3.0/ master >./monopticon-0.3.0.tar.gz
```

**Comment by NSkelsey** [comment]
Using `git bundle create smaller.bundle --all` we can determine precisely the size of the repo. The original precise size on my machine was 102MB with 8026 objects.

Using `git-filter-branch`, removing all of the gifs, webm, all of the wireshark history, and now unnecessary tar balls the repo is at 1.4MB with 973 objects.
