### ISSUE TITLE
Arch Build Dockerfile

### ISSUE THREAD

**Issue by CarloMara** [NSkelsey/monopticon#3]
Hola, 

I'm working on the arch Dockerfile. I'll use this to track the progress on this work. @NSkelsey  please tell me if you see other issues

- [x] Add `MAKEFLAGS="-j$(nproc)"` flag in `/etc/makepkg.conf`, so we use the highest number of cores available on the system
- [x] Consolidate pacman and yay calls 
- [x] Integrate Zeek build to always have fresh artifacts

**Comment by CarloMara** [comment]
Next steps in road to build Monopticon

- [x] @NSkelsey created `imgui-src` in aur
- [x] Create `monopticon-magnum-integration-git` to compile magnum using `imgui`
- [x] Update packages already installed in the image before building

At this point we should be able to build Monopticon using docker which will be used for CI, but it would be nice to fix the monopticon aur package

**Comment by NSkelsey** [comment]
To take this a step further the following things could be done:

- [ ] the image could be loaded on Docker Hub.
- [ ] the order of operations could be adjusted to optimize the cached steps for common problems encountered during builds.
- [ ] the sed of `-j2` to numprocs could be generalized to match `-j\d` instead.
- [x] Co-ownership and Co-maintenance of `monopticon-magnum-integration` should be negotiated with @CarloMara.

**Comment by CarloMara** [comment]
I've added you as a maintainer of `monopticon-magnum-integration` in the AUR. I've also updated the PKGBUILD accordingly.

Carlo
