### ISSUE TITLE
Glitchy view web render in Firefox - Missing some input handling

### ISSUE THREAD

**Issue by enric0r** [NSkelsey/monopticon#7]
If you try moving the view with your mouse and releasing the left button all the rendered assets seem to shake.
Also if you double click on the screen it freezes.
Tried on Firefox and Chrome(and chromium based) this issue is only with Firefox.

**Comment by NSkelsey** [comment]
I've confirmed the issue. Thanks for reporting ;)

Reproduced on Firefox `v72.02` that provides:

![image](https://user-images.githubusercontent.com/1095794/84261733-92e2ea00-ab1c-11ea-832d-5d8d3b3c5b98.png)



Commit 8ee0ec802 prevents the shaking when the scene is rotated and `mouseRelease` is called.

For the double click issue. I believe the second call to the offscreen framebuffer kills the scene.

`gCtx->_objselect_framebuffer.mapForRead(GL::Framebuffer::ColorAttachment{1})`

Interestingly enough the official [magnum picking example](https://magnum.graphics/showcase/picking/). On which this code is based does not work in Firefox.

@Fl0wBuFf3r0v3r can you share your Firefox version and see if your browser works for the official example?

**Comment by NSkelsey** [comment]
The above commit resolves the double click failure on my machine. It's still not exactly clear what the root cause was.

**Comment by mosra** [comment]
FYI: https://github.com/mosra/magnum-examples/issues/53 -- if you manage to get any progress here, I'll gladly steal that to fix the original example :)
